[package]
name = "deepling-from-scratch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
byteorder = "1.5.0"
ndarray = "0.16.1"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
